doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

        url: 'mysql://root:root@db/symfonyjobs'
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/'
                prefix: 'App\Entity'
                alias: App
