# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    view:
        formats:
            json: true
            xml:  true
        empty_content: 204
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
    serializer: ~
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }