vich_uploader:
    db_driver: orm
    mappings:
        logos:
            uri_prefix: /logos
            upload_destination: '%kernel.project_dir%/public/logos'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer