language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - SYMFONY_PHPUNIT_VERSION="7.0.2"

matrix:
  fast_finish: true
  include:
    - php: 7.2

before_install:
  - composer self-update

install:
  - composer install

script:
  - echo "memory_limit=4G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - ./vendor/bin/phpunit
  - ./bin/console lint:yaml config
  - ./bin/console lint:twig templates
  - ./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock
  - composer validate --strict
  - ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction