index:
    path: /
    controller: App\Controller\HomeController::index

#   Auth
action.register:
    path: /register
    methods: [POST]
    controller: App\Controller\Auth\RegisterAgentAction

#   Job
action.job_show_list:
    path: /jobs
    methods: [GET]
    controller: App\Controller\Job\ShowJobsAction

action.job_create:
    path: /jobs
    methods: [POST]
    controller: App\Controller\Job\CreateJobAction

action.job_edit:
    path: /job/{id}
    methods: [PUT]
    controller: App\Controller\Job\EditJobAction

#   Company
action.create_company:
    path: /company
    methods: [POST]
    controller: App\Controller\Job\CreateCompanyAction

action.company_edit:
    path: /company/{id}
    methods: [PUT]
    controller: App\Controller\Company\EditCompanyAction