index_placeholder:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: index.html.twig

api_login_check:
    path: /api/login_check

api:
    resource: "routes/api.yml"
    prefix: /api
