# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false
        bind:
          $validationErrorViewClass: App\View\ValidationErrorView
          $debug: true
          League\Tactician\CommandBus: '@tactician.commandbus.default'
          App\Factory\ValidationErrorViewFactoryInterface:  '@App\Factory\ValidationErrorViewFactory'
          FOS\RestBundle\Util\ExceptionValueMap: '@fos_rest.exception.codes_map'
          FOS\UserBundle\Util\CanonicalizerInterface: '@fos_user.util.canonicalizer.default'
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php,Handler}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Handler\:
        resource: '../src/Handler'
        tags:
            - {name : 'tactician.handler', typehints: true}

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
