#!/usr/bin/env php
<?php

set_time_limit(0);

require_once __DIR__ . "/../../vendor/autoload.php";
require_once __DIR__.'/TestKernel.php';

use App\Tests\App\TestKernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();

$application = new Application(new TestKernel('test', true));
$application->run($input);